### ISSUE TITLE
audit logins?

### ISSUE THREAD

**Issue by walpino** [2ndQuadrant/pgaudit#4] opened 2015-02-09 13:01 UTC
Hi we are using pgaudit (thanks for the great extension)
1. is it possible to audit logins of certain roles as well?
2. permission denied selects it doesn't log, (postgres server does it log but not pgaudit)
3. despite my configuration  in the postgresql.conf pgaudit.roles = 'user1' it audits different user as well
   do you have any reason?

thanks

**Comment by amenonsen** [comment] 2015-02-10 05:14
1. No.
2. Unfortunately, logging queries that are denied is not possible in Postgres right now.
3. Too little information to comment.

**Comment by walpino** [comment] 2015-02-10 10:28
3. we have user1, user2, user3 ....

in the postgresql.conf we have configured that it should only audit user1

pgaudit.roles = 'user1' 

but in the /..../pgsql/logs/postgresql..log there are entries from a different user

2015-02-10 11:14:58 CET LOG:  AUDIT,2015-02-10 11:14:58.365703+01,user2,db1,schema1,READ,SELECT,.... records

**Comment by dup2** [comment] 2015-02-12 13:43
Starting at line 532 of pgaudit.c, there are checks to set the flag ``e.granted`` which might be the cause of the issue, this flag is used to log an audit event regardless of the user/role.

**Comment by dup2** [comment] 2015-02-18 13:48
I found two possible issues with this, @amenonsen  - can you confirm this?

* The call to ``is_member_of_role`` will return true for a superuser, thus the statements of the user "postgres" are all audited
* The fallback of ``should_be_logged``is true at line 360 so for the configuration above, all actions of user2 are audited as the class is audited and the default value is true even if the role is not in "pgaudit.roles"

**Comment by dup2** [comment] 2015-03-08 21:26
I'm trying to provide a patch for this but I'd need some input for how to handle the superuser case (see comment above) which uses a function outside of pgaudit. @amenonsen, can you give me some feedback on this?

**Comment by amenonsen** [comment] 2015-03-15 17:47
Sorry about the delayed response. Yes, you're right that is_member_of_role returns true for the superuser. I should probably use is_member_of_role_nosuper instead.

**Comment by amenonsen** [comment] 2017-01-11 07:00
I'm closing this issue preparatory to dropping this repository in favour of the pgaudit/pgaudit repository.

**Closed by amenonsen** 2017-01-11 07:00 UTC
